### ISSUE TITLE
Can't use in an isomorphic app (ReferenceError: window is not defined)

### ISSUE THREAD

**Issue by tad-lispy** [hpneo/gmaps.core#1]
Hi.

Thanks for your work. It's very useful as is.

However we are building an isomorphic app with React.js and need our code to be reuseble on front- and back-end. Unfortunately just to `require 'gmaps.core'` in node.js leads to `ReferenceError: window is not defined`.

I understand that it cannot be actually used without browser and DOM, but IMO it should be possible to require it in node.js. Then we would instantiate objects and call actual methods only in frontend code, e.g. `componentDidMount` in case of react components.

What do you think?

**Comment by hpneo** [comment]
You're right, I'm gonna check how to do this and post here any update.

EDIT: If you have some boilerplate app to test this, I would appreciate that.

**Comment by hpneo** [comment]
I removed all the `window` references in the `0.5.1` version, so it should work now.

**Comment by tad-lispy** [comment]
Thanks. I can confirm it's working now.
